# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 19 Oct 2023 21:17:03 +0000
*               @ALL          1
*               @user         8
