<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Thu, 19 Oct 2023 21:17:03 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
