# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Thu, 19 Oct 2023 21:17:03 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

asyncoreproject:$2y$10$19tNzXl2TS02WDg3Npgjd.ZdINnY34o4lawzsoePq4aXHvBDE5GDm:Daniel Alonso Lázaro:asyncoreproject@gmail.com:admin,user
