CREATE PROCEDURE SP_ULTIMOS_HILOS()
BEGIN
    DECLARE NUM_HILOS INT;
    SET NUM_HILOS = 3;
    SELECT ID_HILO, USER_ID, TITULO, CONTENIDO, FECHA_CREACION, FECHA_EDICION, ID_CATEGORIA
    FROM HILOS
    ORDER BY FECHA_EDICION DESC
    LIMIT NUM_HILOS;
END