DELIMITER //
DROP PROCEDURE IF EXISTS SP_ULTIMOS_HILOS;
CREATE PROCEDURE SP_ULTIMOS_HILOS(IN NUM_HILOS INT)
BEGIN
    SELECT ID_HILO, USER_ID, TITULO, CONTENIDO, FECHA_CREACION, FECHA_EDICION, ID_CATEGORIA
    FROM HILOS
    ORDER BY FECHA_CREACION DESC
    LIMIT NUM_HILOS;
END;
DELIMITER ;

CALL SP_ULTIMOS_HILOS(4);