CREATE PROCEDURE TOP_THREADS_BY_POSTS()
BEGIN
    DECLARE NUM_THREADS INT;
    SET NUM_THREADS = 5;
    SELECT HILOS.THREAD_ID, TITULO, COUNT(POSTS.POST_ID) AS NUMERO_POSTS
    FROM HILOS
             LEFT JOIN POSTS ON HILOS.THREAD_ID = POSTS.THREAD_ID
    GROUP BY HILOS.THREAD_ID, TITULO
    ORDER BY NUMERO_POSTS DESC
    LIMIT NUM_THREADS;
END 
