CREATE PROCEDURE SP_CREAR_ULTIMOS_POSTS()
BEGIN
    DROP TABLE IF EXISTS ULTIMOS_POSTS;
    DECLARE NUM_POSTS INT;
    SET NUM_POSTS = 3;


    CREATE TABLE ULTIMOS_POSTS AS
    SELECT ID_HILO, USER_ID, TITULO, CONTENIDO, FECHA_CREACION, FECHA_EDICION, ID_CATEGORIA
    FROM HILOS
    ORDER BY FECHA_CREACION DESC
    LIMIT NUM_POSTS; 
END;

/* Propongo dos versiones de este procedimiento porque 
no tengo muy claro cual es la más óptima de cara al server*/

CREATE PROCEDURE SP_ULTIMOS_POSTS()
BEGIN
    DECLARE NUM_POSTS INT;
    SET NUM_POSTS = 3;

    SELECT ID_HILO, USER_ID, TITULO, CONTENIDO, FECHA_CREACION, FECHA_EDICION, ID_CATEGORIA
    FROM HILOS
    ORDER BY FECHA_CREACION DESC
    LIMIT NUM_POSTS;
END;

