CREATE PROCEDURE SP_TOP_HILOS_CON_MAS_POSTS()
BEGIN
    DECLARE NUM_THREADS INT;
    SET NUM_THREADS = 5;
    SELECT HILOS.ID_HILO, TITULO, COUNT(POSTS.ID_POST) AS NUMERO_POSTS
    FROM HILOS
    LEFT JOIN POSTS ON HILOS.ID_HILO = POSTS.ID_HILO
    GROUP BY HILOS.ID_HILO, TITULO
    ORDER BY NUMERO_POSTS DESC
    LIMIT NUM_THREADS;
END 
