DELIMITER //
DROP PROCEDURE IF EXISTS LATEST_THREADS;
CREATE PROCEDURE LATEST_THREADS(IN NUM_HILOS INT)
BEGIN
    SELECT THREAD_ID, USER_ID, TITULO, CONTENIDO, F_CRE, F_EDI, CAT_ID
    FROM HILOS
    ORDER BY F_CRE DESC
    LIMIT NUM_HILOS;
END;
DELIMITER ;